### PR TITLE
Use ros::ok() and ros::spinOnce()

### PR DESCRIPTION
**Pull request by naoki-mizuno**
With this change, the node can be shut down with Ctrl-c.

Reference:
http://wiki.ros.org/roscpp/Overview/Initialization%20and%20Shutdown

### CODE REVIEW

**Comment by juliangaal** [comment]
would there be a difference between `spinOnce()` and `spin()` in this instance?

**Comment by naoki-mizuno** [comment]
@juliangaal `spin()` blocks the execution so it's used when there are only subscribers left to do the job. In this case, the while loop needs to keep spinning, so `spinOnce()` is used.

**Comment by juliangaal** [comment]
Ah, thanks. Have a nice day

**Review by an-scott — APPROVED** [review]
Thank you

**Pull request merged**
